ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.lido_withdrawal_anomaly]
path = "out/LidoWithdrawalAnomalyTrap.sol/LidoWithdrawalAnomalyTrap.json"
response_contract = "0x66cda304263fb0112622769c512f97e6aba65010"
response_function = "handleWithdrawalAnomaly(string,bytes)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x0048165e769a0Dc571e082B80A51e3e6E7E0Aa82"]
